/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11MeshHelpers21renderMeshImmediatelyER13ScreenContextR11TessellatorRKN3mce11MaterialPtrERKN6nonstd8variants7variantINS9_9monostateENS4_10TexturePtrENS4_13ClientTextureENS4_13ServerTextureENS9_6detail2TXINSF_2S4EEENSG_INSF_2S5EEENSG_INSF_2S6EEENSG_INSF_2S7EEENSG_INSF_2S8EEENSG_INSF_2S9EEENSG_INSF_3S10EEENSG_INSF_3S11EEENSG_INSF_3S12EEENSG_INSF_3S13EEENSG_INSF_3S14EEENSG_INSF_3S15EEEEENSt6__ndk18functionIFvRKS0_RKNS4_4MeshES7_S17_EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN11MeshHelpers21renderMeshImmediatelyER13ScreenContextR11TessellatorRKN3mce11MaterialPtrERKN6nonstd8variants7variantINS9_9monostateENS4_10TexturePtrENS4_13ClientTextureENS4_13ServerTextureENS9_6detail2TXINSF_2S4EEENSG_INSF_2S5EEENSG_INSF_2S6EEENSG_INSF_2S7EEENSG_INSF_2S8EEENSG_INSF_2S9EEENSG_INSF_3S10EEENSG_INSF_3S11EEENSG_INSF_3S12EEENSG_INSF_3S13EEENSG_INSF_3S14EEENSG_INSF_3S15EEEEENSt6__ndk18functionIFvRKS0_RKNS4_4MeshES7_S17_EEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN11MeshHelpers21renderMeshImmediatelyER13ScreenContextR11TessellatorRKN3mce11MaterialPtrERKN6nonstd8variants7variantINS9_9monostateENS4_10TexturePtrENS4_13ClientTextureENS4_13ServerTextureENS9_6detail2TXINSF_2S4EEENSG_INSF_2S5EEENSG_INSF_2S6EEENSG_INSF_2S7EEENSG_INSF_2S8EEENSG_INSF_2S9EEENSG_INSF_3S10EEENSG_INSF_3S11EEENSG_INSF_3S12EEENSG_INSF_3S13EEENSG_INSF_3S14EEENSG_INSF_3S15EEEEENSt6__ndk18functionIFvRKS0_RKNS4_4MeshES7_S17_EEE()');
  },

  /**
   * Called synchronously when about to return from _ZN11MeshHelpers21renderMeshImmediatelyER13ScreenContextR11TessellatorRKN3mce11MaterialPtrERKN6nonstd8variants7variantINS9_9monostateENS4_10TexturePtrENS4_13ClientTextureENS4_13ServerTextureENS9_6detail2TXINSF_2S4EEENSG_INSF_2S5EEENSG_INSF_2S6EEENSG_INSF_2S7EEENSG_INSF_2S8EEENSG_INSF_2S9EEENSG_INSF_3S10EEENSG_INSF_3S11EEENSG_INSF_3S12EEENSG_INSF_3S13EEENSG_INSF_3S14EEENSG_INSF_3S15EEEEENSt6__ndk18functionIFvRKS0_RKNS4_4MeshES7_S17_EEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
