/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN24EDULibraryCategoryParser13getCategoriesERNSt6__ndk113unordered_mapINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE18EDULibraryCategoryNS0_4hashIS7_EENS0_8equal_toIS7_EENS5_INS0_4pairIKS7_S8_EEEEEERSE_NS0_8functionIFvNS0_10shared_ptrI19MainMenuScreenModelEES7_S7_S7_S7_iNS0_6vectorIS7_NS5_IS7_EEEEbEEENSK_IFvSN_S7_S7_S7_SQ_EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN24EDULibraryCategoryParser13getCategoriesERNSt6__ndk113unordered_mapINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE18EDULibraryCategoryNS0_4hashIS7_EENS0_8equal_toIS7_EENS5_INS0_4pairIKS7_S8_EEEEEERSE_NS0_8functionIFvNS0_10shared_ptrI19MainMenuScreenModelEES7_S7_S7_S7_iNS0_6vectorIS7_NS5_IS7_EEEEbEEENSK_IFvSN_S7_S7_S7_SQ_EEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN24EDULibraryCategoryParser13getCategoriesERNSt6__ndk113unordered_mapINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE18EDULibraryCategoryNS0_4hashIS7_EENS0_8equal_toIS7_EENS5_INS0_4pairIKS7_S8_EEEEEERSE_NS0_8functionIFvNS0_10shared_ptrI19MainMenuScreenModelEES7_S7_S7_S7_iNS0_6vectorIS7_NS5_IS7_EEEEbEEENSK_IFvSN_S7_S7_S7_SQ_EEE()');
  },

  /**
   * Called synchronously when about to return from _ZN24EDULibraryCategoryParser13getCategoriesERNSt6__ndk113unordered_mapINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE18EDULibraryCategoryNS0_4hashIS7_EENS0_8equal_toIS7_EENS5_INS0_4pairIKS7_S8_EEEEEERSE_NS0_8functionIFvNS0_10shared_ptrI19MainMenuScreenModelEES7_S7_S7_S7_iNS0_6vectorIS7_NS5_IS7_EEEEbEEENSK_IFvSN_S7_S7_S7_SQ_EEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
