/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_31RenderFlameBillboardDescriptionEEENS6_IKNS0_30BlitFlipbookTextureDescriptionEEENS6_IKNS0_25RenderParticleDescriptionEEENS6_IKNS0_23RenderShadowDescriptionEEENS3_6detail2TXINSJ_2S4EEENSK_INSJ_2S5EEENSK_INSJ_2S6EEENSK_INSJ_2S7EEENSK_INSJ_2S8EEENSK_INSJ_2S9EEENSK_INSJ_3S10EEENSK_INSJ_3S11EEENSK_INSJ_3S12EEENSK_INSJ_3S13EEENSK_INSJ_3S14EEENSK_INSJ_3S15EEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_31RenderFlameBillboardDescriptionEEENS6_IKNS0_30BlitFlipbookTextureDescriptionEEENS6_IKNS0_25RenderParticleDescriptionEEENS6_IKNS0_23RenderShadowDescriptionEEENS3_6detail2TXINSJ_2S4EEENSK_INSJ_2S5EEENSK_INSJ_2S6EEENSK_INSJ_2S7EEENSK_INSJ_2S8EEENSK_INSJ_2S9EEENSK_INSJ_3S10EEENSK_INSJ_3S11EEENSK_INSJ_3S12EEENSK_INSJ_3S13EEENSK_INSJ_3S14EEENSK_INSJ_3S15EEEEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_31RenderFlameBillboardDescriptionEEENS6_IKNS0_30BlitFlipbookTextureDescriptionEEENS6_IKNS0_25RenderParticleDescriptionEEENS6_IKNS0_23RenderShadowDescriptionEEENS3_6detail2TXINSJ_2S4EEENSK_INSJ_2S5EEENSK_INSJ_2S6EEENSK_INSJ_2S7EEENSK_INSJ_2S8EEENSK_INSJ_2S9EEENSK_INSJ_3S10EEENSK_INSJ_3S11EEENSK_INSJ_3S12EEENSK_INSJ_3S13EEENSK_INSJ_3S14EEENSK_INSJ_3S15EEEEE()');
  },

  /**
   * Called synchronously when about to return from _ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_31RenderFlameBillboardDescriptionEEENS6_IKNS0_30BlitFlipbookTextureDescriptionEEENS6_IKNS0_25RenderParticleDescriptionEEENS6_IKNS0_23RenderShadowDescriptionEEENS3_6detail2TXINSJ_2S4EEENSK_INSJ_2S5EEENSK_INSJ_2S6EEENSK_INSJ_2S7EEENSK_INSJ_2S8EEENSK_INSJ_2S9EEENSK_INSJ_3S10EEENSK_INSJ_3S11EEENSK_INSJ_3S12EEENSK_INSJ_3S13EEENSK_INSJ_3S14EEENSK_INSJ_3S15EEEEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
