/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3mce25ServerSideResourceServiceINS_31AssertServerSideResourceHandlerEE6unwrapINS_15ResourcePointerIN6nonstd8variants7variantINS6_9monostateENS_6BufferENS_21ClientResourcePointerINS4_IN6dragon4mesh28ResolvedVertexBufferResourceENS_21ResourceBlockTemplateISD_NS_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENSt6__ndk110shared_ptrEEEEENSA_INS4_INSC_27ResolvedIndexBufferResourceENSE_ISM_SF_SG_EESJ_EEEENS6_6detail2TXINSQ_2S4EEENSR_INSQ_2S5EEENSR_INSQ_2S6EEENSR_INSQ_2S7EEENSR_INSQ_2S8EEENSR_INSQ_2S9EEENSR_INSQ_3S10EEENSR_INSQ_3S11EEENSR_INSQ_3S12EEENSR_INSQ_3S13EEENSR_INSQ_3S14EEENSR_INSQ_3S15EEEEENSE_IS1G_NS_21PerFrameHandleTrackerESG_EESJ_EEEEPNT_8ResourceERKS1K_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN3mce25ServerSideResourceServiceINS_31AssertServerSideResourceHandlerEE6unwrapINS_15ResourcePointerIN6nonstd8variants7variantINS6_9monostateENS_6BufferENS_21ClientResourcePointerINS4_IN6dragon4mesh28ResolvedVertexBufferResourceENS_21ResourceBlockTemplateISD_NS_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENSt6__ndk110shared_ptrEEEEENSA_INS4_INSC_27ResolvedIndexBufferResourceENSE_ISM_SF_SG_EESJ_EEEENS6_6detail2TXINSQ_2S4EEENSR_INSQ_2S5EEENSR_INSQ_2S6EEENSR_INSQ_2S7EEENSR_INSQ_2S8EEENSR_INSQ_2S9EEENSR_INSQ_3S10EEENSR_INSQ_3S11EEENSR_INSQ_3S12EEENSR_INSQ_3S13EEENSR_INSQ_3S14EEENSR_INSQ_3S15EEEEENSE_IS1G_NS_21PerFrameHandleTrackerESG_EESJ_EEEEPNT_8ResourceERKS1K_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN3mce25ServerSideResourceServiceINS_31AssertServerSideResourceHandlerEE6unwrapINS_15ResourcePointerIN6nonstd8variants7variantINS6_9monostateENS_6BufferENS_21ClientResourcePointerINS4_IN6dragon4mesh28ResolvedVertexBufferResourceENS_21ResourceBlockTemplateISD_NS_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENSt6__ndk110shared_ptrEEEEENSA_INS4_INSC_27ResolvedIndexBufferResourceENSE_ISM_SF_SG_EESJ_EEEENS6_6detail2TXINSQ_2S4EEENSR_INSQ_2S5EEENSR_INSQ_2S6EEENSR_INSQ_2S7EEENSR_INSQ_2S8EEENSR_INSQ_2S9EEENSR_INSQ_3S10EEENSR_INSQ_3S11EEENSR_INSQ_3S12EEENSR_INSQ_3S13EEENSR_INSQ_3S14EEENSR_INSQ_3S15EEEEENSE_IS1G_NS_21PerFrameHandleTrackerESG_EESJ_EEEEPNT_8ResourceERKS1K_()');
  },

  /**
   * Called synchronously when about to return from _ZN3mce25ServerSideResourceServiceINS_31AssertServerSideResourceHandlerEE6unwrapINS_15ResourcePointerIN6nonstd8variants7variantINS6_9monostateENS_6BufferENS_21ClientResourcePointerINS4_IN6dragon4mesh28ResolvedVertexBufferResourceENS_21ResourceBlockTemplateISD_NS_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENSt6__ndk110shared_ptrEEEEENSA_INS4_INSC_27ResolvedIndexBufferResourceENSE_ISM_SF_SG_EESJ_EEEENS6_6detail2TXINSQ_2S4EEENSR_INSQ_2S5EEENSR_INSQ_2S6EEENSR_INSQ_2S7EEENSR_INSQ_2S8EEENSR_INSQ_2S9EEENSR_INSQ_3S10EEENSR_INSQ_3S11EEENSR_INSQ_3S12EEENSR_INSQ_3S13EEENSR_INSQ_3S14EEENSR_INSQ_3S15EEEEENSE_IS1G_NS_21PerFrameHandleTrackerESG_EESJ_EEEEPNT_8ResourceERKS1K_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
