/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_24RenderCubemapDescriptionEEENS6_IKNS0_23RenderEndSkyDescriptionEEENS6_IKNS0_30RenderLegacyCubemapDescriptionEEENS6_IKNS0_20RenderSkyDescriptionEEENS6_IKNS0_22RenderStarsDescriptionEEENS6_IKNS0_24RenderSunMoonDescriptionEEENS6_IKNS0_24RenderWeatherDescriptionEEENS3_6detail2TXINSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_24RenderCubemapDescriptionEEENS6_IKNS0_23RenderEndSkyDescriptionEEENS6_IKNS0_30RenderLegacyCubemapDescriptionEEENS6_IKNS0_20RenderSkyDescriptionEEENS6_IKNS0_22RenderStarsDescriptionEEENS6_IKNS0_24RenderSunMoonDescriptionEEENS6_IKNS0_24RenderWeatherDescriptionEEENS3_6detail2TXINSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_24RenderCubemapDescriptionEEENS6_IKNS0_23RenderEndSkyDescriptionEEENS6_IKNS0_30RenderLegacyCubemapDescriptionEEENS6_IKNS0_20RenderSkyDescriptionEEENS6_IKNS0_22RenderStarsDescriptionEEENS6_IKNS0_24RenderSunMoonDescriptionEEENS6_IKNS0_24RenderWeatherDescriptionEEENS3_6detail2TXINSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEE()');
  },

  /**
   * Called synchronously when about to return from _ZN3mce12framebuilder16NullFrameBuilder7_insertEN6nonstd8variants7variantINSt6__ndk117reference_wrapperIKNS0_24RenderCubemapDescriptionEEENS6_IKNS0_23RenderEndSkyDescriptionEEENS6_IKNS0_30RenderLegacyCubemapDescriptionEEENS6_IKNS0_20RenderSkyDescriptionEEENS6_IKNS0_22RenderStarsDescriptionEEENS6_IKNS0_24RenderSunMoonDescriptionEEENS6_IKNS0_24RenderWeatherDescriptionEEENS3_6detail2TXINSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
