/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3mce20TransactionContainerINS_23CreateBufferTransactionENS_21BufferResourceServiceENS_24ImmediateExecutionPolicyEEC2ENSt6__ndk18weak_ptrINS_21ResourceBlockTemplateIN6nonstd8variants7variantINS9_9monostateENS_6BufferENS_21ClientResourcePointerINS_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS7_ISH_NS_22UncheckedHandleTrackerENSF_17BufferDescriptionEEENS5_10shared_ptrEEEEENSD_INSE_INSG_27ResolvedIndexBufferResourceENS7_ISO_SI_SJ_EESL_EEEENS9_6detail2TXINSS_2S4EEENST_INSS_2S5EEENST_INSS_2S6EEENST_INSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEENS_21PerFrameHandleTrackerESJ_EEEEOKNS5_8functionIFvRS1_EEEPNS_28BufferResourceServiceContextE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN3mce20TransactionContainerINS_23CreateBufferTransactionENS_21BufferResourceServiceENS_24ImmediateExecutionPolicyEEC2ENSt6__ndk18weak_ptrINS_21ResourceBlockTemplateIN6nonstd8variants7variantINS9_9monostateENS_6BufferENS_21ClientResourcePointerINS_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS7_ISH_NS_22UncheckedHandleTrackerENSF_17BufferDescriptionEEENS5_10shared_ptrEEEEENSD_INSE_INSG_27ResolvedIndexBufferResourceENS7_ISO_SI_SJ_EESL_EEEENS9_6detail2TXINSS_2S4EEENST_INSS_2S5EEENST_INSS_2S6EEENST_INSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEENS_21PerFrameHandleTrackerESJ_EEEEOKNS5_8functionIFvRS1_EEEPNS_28BufferResourceServiceContextE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN3mce20TransactionContainerINS_23CreateBufferTransactionENS_21BufferResourceServiceENS_24ImmediateExecutionPolicyEEC2ENSt6__ndk18weak_ptrINS_21ResourceBlockTemplateIN6nonstd8variants7variantINS9_9monostateENS_6BufferENS_21ClientResourcePointerINS_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS7_ISH_NS_22UncheckedHandleTrackerENSF_17BufferDescriptionEEENS5_10shared_ptrEEEEENSD_INSE_INSG_27ResolvedIndexBufferResourceENS7_ISO_SI_SJ_EESL_EEEENS9_6detail2TXINSS_2S4EEENST_INSS_2S5EEENST_INSS_2S6EEENST_INSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEENS_21PerFrameHandleTrackerESJ_EEEEOKNS5_8functionIFvRS1_EEEPNS_28BufferResourceServiceContextE()');
  },

  /**
   * Called synchronously when about to return from _ZN3mce20TransactionContainerINS_23CreateBufferTransactionENS_21BufferResourceServiceENS_24ImmediateExecutionPolicyEEC2ENSt6__ndk18weak_ptrINS_21ResourceBlockTemplateIN6nonstd8variants7variantINS9_9monostateENS_6BufferENS_21ClientResourcePointerINS_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS7_ISH_NS_22UncheckedHandleTrackerENSF_17BufferDescriptionEEENS5_10shared_ptrEEEEENSD_INSE_INSG_27ResolvedIndexBufferResourceENS7_ISO_SI_SJ_EESL_EEEENS9_6detail2TXINSS_2S4EEENST_INSS_2S5EEENST_INSS_2S6EEENST_INSS_2S7EEENST_INSS_2S8EEENST_INSS_2S9EEENST_INSS_3S10EEENST_INSS_3S11EEENST_INSS_3S12EEENST_INSS_3S13EEENST_INSS_3S14EEENST_INSS_3S15EEEEENS_21PerFrameHandleTrackerESJ_EEEEOKNS5_8functionIFvRS1_EEEPNS_28BufferResourceServiceContextE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
