/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4xbox8services9JsonUtils17ExtractJsonVectorINS0_15user_statistics20UserStatisticsResultEPFNS0_6ResultIS4_EERKN9rapidjson12GenericValueINS7_4UTF8IcEENS7_19MemoryPoolAllocatorINS7_12CrtAllocatorEEEEEEEEiT0_SG_RKNSt6__ndk112basic_stringIcNSK_11char_traitsIcEENS0_9AllocatorIcEEEERNSK_6vectorIT_NSO_ISU_EEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN4xbox8services9JsonUtils17ExtractJsonVectorINS0_15user_statistics20UserStatisticsResultEPFNS0_6ResultIS4_EERKN9rapidjson12GenericValueINS7_4UTF8IcEENS7_19MemoryPoolAllocatorINS7_12CrtAllocatorEEEEEEEEiT0_SG_RKNSt6__ndk112basic_stringIcNSK_11char_traitsIcEENS0_9AllocatorIcEEEERNSK_6vectorIT_NSO_ISU_EEEEb.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN4xbox8services9JsonUtils17ExtractJsonVectorINS0_15user_statistics20UserStatisticsResultEPFNS0_6ResultIS4_EERKN9rapidjson12GenericValueINS7_4UTF8IcEENS7_19MemoryPoolAllocatorINS7_12CrtAllocatorEEEEEEEEiT0_SG_RKNSt6__ndk112basic_stringIcNSK_11char_traitsIcEENS0_9AllocatorIcEEEERNSK_6vectorIT_NSO_ISU_EEEEb()');
  },

  /**
   * Called synchronously when about to return from _ZN4xbox8services9JsonUtils17ExtractJsonVectorINS0_15user_statistics20UserStatisticsResultEPFNS0_6ResultIS4_EERKN9rapidjson12GenericValueINS7_4UTF8IcEENS7_19MemoryPoolAllocatorINS7_12CrtAllocatorEEEEEEEEiT0_SG_RKNSt6__ndk112basic_stringIcNSK_11char_traitsIcEENS0_9AllocatorIcEEEERNSK_6vectorIT_NSO_ISU_EEEEb.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
