/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4xbox8services11multiplayer7manager26SetLocalMemberPropsContextC2ENSt6__ndk110shared_ptrINS2_21MultiplayerGameClientEEENS5_INS2_20MultiplayerLocalUserEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS0_9AllocatorIcEEEERKNS4_3mapISF_N9rapidjson15GenericDocumentINSJ_4UTF8IcEENSJ_19MemoryPoolAllocatorINSJ_12CrtAllocatorEEESO_EENS4_4lessISF_EENSD_INS4_4pairISG_SQ_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN4xbox8services11multiplayer7manager26SetLocalMemberPropsContextC2ENSt6__ndk110shared_ptrINS2_21MultiplayerGameClientEEENS5_INS2_20MultiplayerLocalUserEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS0_9AllocatorIcEEEERKNS4_3mapISF_N9rapidjson15GenericDocumentINSJ_4UTF8IcEENSJ_19MemoryPoolAllocatorINSJ_12CrtAllocatorEEESO_EENS4_4lessISF_EENSD_INS4_4pairISG_SQ_EEEEEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN4xbox8services11multiplayer7manager26SetLocalMemberPropsContextC2ENSt6__ndk110shared_ptrINS2_21MultiplayerGameClientEEENS5_INS2_20MultiplayerLocalUserEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS0_9AllocatorIcEEEERKNS4_3mapISF_N9rapidjson15GenericDocumentINSJ_4UTF8IcEENSJ_19MemoryPoolAllocatorINSJ_12CrtAllocatorEEESO_EENS4_4lessISF_EENSD_INS4_4pairISG_SQ_EEEEEE()');
  },

  /**
   * Called synchronously when about to return from _ZN4xbox8services11multiplayer7manager26SetLocalMemberPropsContextC2ENSt6__ndk110shared_ptrINS2_21MultiplayerGameClientEEENS5_INS2_20MultiplayerLocalUserEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS0_9AllocatorIcEEEERKNS4_3mapISF_N9rapidjson15GenericDocumentINSJ_4UTF8IcEENSJ_19MemoryPoolAllocatorINSJ_12CrtAllocatorEEESO_EENS4_4lessISF_EENSD_INS4_4pairISG_SQ_EEEEEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
