/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6nonstd8variants6detail10ComparatorINS0_7variantI13ActorUniqueIDNSt6__ndk14pairI8BlockPos11AutomaticIDI9DimensioniEEENS1_2TXINS1_2S2EEENSC_INS1_2S3EEENSC_INS1_2S4EEENSC_INS1_2S5EEENSC_INS1_2S6EEENSC_INS1_2S7EEENSC_INS1_2S8EEENSC_INS1_2S9EEENSC_INS1_3S10EEENSC_INS1_3S11EEENSC_INS1_3S12EEENSC_INS1_3S13EEENSC_INS1_3S14EEENSC_INS1_3S15EEEEEE5equalERKS15_S18_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN6nonstd8variants6detail10ComparatorINS0_7variantI13ActorUniqueIDNSt6__ndk14pairI8BlockPos11AutomaticIDI9DimensioniEEENS1_2TXINS1_2S2EEENSC_INS1_2S3EEENSC_INS1_2S4EEENSC_INS1_2S5EEENSC_INS1_2S6EEENSC_INS1_2S7EEENSC_INS1_2S8EEENSC_INS1_2S9EEENSC_INS1_3S10EEENSC_INS1_3S11EEENSC_INS1_3S12EEENSC_INS1_3S13EEENSC_INS1_3S14EEENSC_INS1_3S15EEEEEE5equalERKS15_S18_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN6nonstd8variants6detail10ComparatorINS0_7variantI13ActorUniqueIDNSt6__ndk14pairI8BlockPos11AutomaticIDI9DimensioniEEENS1_2TXINS1_2S2EEENSC_INS1_2S3EEENSC_INS1_2S4EEENSC_INS1_2S5EEENSC_INS1_2S6EEENSC_INS1_2S7EEENSC_INS1_2S8EEENSC_INS1_2S9EEENSC_INS1_3S10EEENSC_INS1_3S11EEENSC_INS1_3S12EEENSC_INS1_3S13EEENSC_INS1_3S14EEENSC_INS1_3S15EEEEEE5equalERKS15_S18_()');
  },

  /**
   * Called synchronously when about to return from _ZN6nonstd8variants6detail10ComparatorINS0_7variantI13ActorUniqueIDNSt6__ndk14pairI8BlockPos11AutomaticIDI9DimensioniEEENS1_2TXINS1_2S2EEENSC_INS1_2S3EEENSC_INS1_2S4EEENSC_INS1_2S5EEENSC_INS1_2S6EEENSC_INS1_2S7EEENSC_INS1_2S8EEENSC_INS1_2S9EEENSC_INS1_3S10EEENSC_INS1_3S11EEENSC_INS1_3S12EEENSC_INS1_3S13EEENSC_INS1_3S14EEENSC_INS1_3S15EEEEEE5equalERKS15_S18_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
