/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6nonstd8variants7variantI18ButtonIndiciesEnum19TriggerIndiciesEnumNS0_6detail2TXINS4_2S2EEENS5_INS4_2S3EEENS5_INS4_2S4EEENS5_INS4_2S5EEENS5_INS4_2S6EEENS5_INS4_2S7EEENS5_INS4_2S8EEENS5_INS4_2S9EEENS5_INS4_3S10EEENS5_INS4_3S11EEENS5_INS4_3S12EEENS5_INS4_3S13EEENS5_INS4_3S14EEENS5_INS4_3S15EEEEC2ERKSY_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN6nonstd8variants7variantI18ButtonIndiciesEnum19TriggerIndiciesEnumNS0_6detail2TXINS4_2S2EEENS5_INS4_2S3EEENS5_INS4_2S4EEENS5_INS4_2S5EEENS5_INS4_2S6EEENS5_INS4_2S7EEENS5_INS4_2S8EEENS5_INS4_2S9EEENS5_INS4_3S10EEENS5_INS4_3S11EEENS5_INS4_3S12EEENS5_INS4_3S13EEENS5_INS4_3S14EEENS5_INS4_3S15EEEEC2ERKSY_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZN6nonstd8variants7variantI18ButtonIndiciesEnum19TriggerIndiciesEnumNS0_6detail2TXINS4_2S2EEENS5_INS4_2S3EEENS5_INS4_2S4EEENS5_INS4_2S5EEENS5_INS4_2S6EEENS5_INS4_2S7EEENS5_INS4_2S8EEENS5_INS4_2S9EEENS5_INS4_3S10EEENS5_INS4_3S11EEENS5_INS4_3S12EEENS5_INS4_3S13EEENS5_INS4_3S14EEENS5_INS4_3S15EEEEC2ERKSY_()');
  },

  /**
   * Called synchronously when about to return from _ZN6nonstd8variants7variantI18ButtonIndiciesEnum19TriggerIndiciesEnumNS0_6detail2TXINS4_2S2EEENS5_INS4_2S3EEENS5_INS4_2S4EEENS5_INS4_2S5EEENS5_INS4_2S6EEENS5_INS4_2S7EEENS5_INS4_2S8EEENS5_INS4_2S9EEENS5_INS4_3S10EEENS5_INS4_3S11EEENS5_INS4_3S12EEENS5_INS4_3S13EEENS5_INS4_3S14EEENS5_INS4_3S15EEEEC2ERKSY_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
