/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3mce4Mesh10renderMeshERNS_11MeshContextERKN6dragon14RenderMetadataERKNS_11MaterialPtrERKN6nonstd8variants7variantINSB_9monostateENS_10TexturePtrENS_13ClientTextureENS_13ServerTextureENSB_6detail2TXINSH_2S4EEENSI_INSH_2S5EEENSI_INSH_2S6EEENSI_INSH_2S7EEENSI_INSH_2S8EEENSI_INSH_2S9EEENSI_INSH_3S10EEENSI_INSH_3S11EEENSI_INSH_3S12EEENSI_INSH_3S13EEENSI_INSH_3S14EEENSI_INSH_3S15EEEEEjjPKNS_20IndexBufferContainerE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNK3mce4Mesh10renderMeshERNS_11MeshContextERKN6dragon14RenderMetadataERKNS_11MaterialPtrERKN6nonstd8variants7variantINSB_9monostateENS_10TexturePtrENS_13ClientTextureENS_13ServerTextureENSB_6detail2TXINSH_2S4EEENSI_INSH_2S5EEENSI_INSH_2S6EEENSI_INSH_2S7EEENSI_INSH_2S8EEENSI_INSH_2S9EEENSI_INSH_3S10EEENSI_INSH_3S11EEENSI_INSH_3S12EEENSI_INSH_3S13EEENSI_INSH_3S14EEENSI_INSH_3S15EEEEEjjPKNS_20IndexBufferContainerE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNK3mce4Mesh10renderMeshERNS_11MeshContextERKN6dragon14RenderMetadataERKNS_11MaterialPtrERKN6nonstd8variants7variantINSB_9monostateENS_10TexturePtrENS_13ClientTextureENS_13ServerTextureENSB_6detail2TXINSH_2S4EEENSI_INSH_2S5EEENSI_INSH_2S6EEENSI_INSH_2S7EEENSI_INSH_2S8EEENSI_INSH_2S9EEENSI_INSH_3S10EEENSI_INSH_3S11EEENSI_INSH_3S12EEENSI_INSH_3S13EEENSI_INSH_3S14EEENSI_INSH_3S15EEEEEjjPKNS_20IndexBufferContainerE()');
  },

  /**
   * Called synchronously when about to return from _ZNK3mce4Mesh10renderMeshERNS_11MeshContextERKN6dragon14RenderMetadataERKNS_11MaterialPtrERKN6nonstd8variants7variantINSB_9monostateENS_10TexturePtrENS_13ClientTextureENS_13ServerTextureENSB_6detail2TXINSH_2S4EEENSI_INSH_2S5EEENSI_INSH_2S6EEENSI_INSH_2S7EEENSI_INSH_2S8EEENSI_INSH_2S9EEENSI_INSH_3S10EEENSI_INSH_3S11EEENSI_INSH_3S12EEENSI_INSH_3S13EEENSI_INSH_3S14EEENSI_INSH_3S15EEEEEjjPKNS_20IndexBufferContainerE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
