/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk112__hash_tableINS_17__hash_value_typeI12LegacyOptionN6nonstd8variants7variantIbhjNS4_6detail2TXINS6_2S3EEENS7_INS6_2S4EEENS7_INS6_2S5EEENS7_INS6_2S6EEENS7_INS6_2S7EEENS7_INS6_2S8EEENS7_INS6_2S9EEENS7_INS6_3S10EEENS7_INS6_3S11EEENS7_INS6_3S12EEENS7_INS6_3S13EEENS7_INS6_3S14EEENS7_INS6_3S15EEEEEEENS_22__unordered_map_hasherIS2_SZ_NS_4hashIS2_EELb1EEENS_21__unordered_map_equalIS2_SZ_NS_8equal_toIS2_EELb1EEENS_9allocatorISZ_EEE21__construct_node_hashIS2_JbEEENS_10unique_ptrINS_11__hash_nodeISZ_PvEENS_22__hash_node_destructorINS18_IS1F_EEEEEEjOT_DpOT0_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk112__hash_tableINS_17__hash_value_typeI12LegacyOptionN6nonstd8variants7variantIbhjNS4_6detail2TXINS6_2S3EEENS7_INS6_2S4EEENS7_INS6_2S5EEENS7_INS6_2S6EEENS7_INS6_2S7EEENS7_INS6_2S8EEENS7_INS6_2S9EEENS7_INS6_3S10EEENS7_INS6_3S11EEENS7_INS6_3S12EEENS7_INS6_3S13EEENS7_INS6_3S14EEENS7_INS6_3S15EEEEEEENS_22__unordered_map_hasherIS2_SZ_NS_4hashIS2_EELb1EEENS_21__unordered_map_equalIS2_SZ_NS_8equal_toIS2_EELb1EEENS_9allocatorISZ_EEE21__construct_node_hashIS2_JbEEENS_10unique_ptrINS_11__hash_nodeISZ_PvEENS_22__hash_node_destructorINS18_IS1F_EEEEEEjOT_DpOT0_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk112__hash_tableINS_17__hash_value_typeI12LegacyOptionN6nonstd8variants7variantIbhjNS4_6detail2TXINS6_2S3EEENS7_INS6_2S4EEENS7_INS6_2S5EEENS7_INS6_2S6EEENS7_INS6_2S7EEENS7_INS6_2S8EEENS7_INS6_2S9EEENS7_INS6_3S10EEENS7_INS6_3S11EEENS7_INS6_3S12EEENS7_INS6_3S13EEENS7_INS6_3S14EEENS7_INS6_3S15EEEEEEENS_22__unordered_map_hasherIS2_SZ_NS_4hashIS2_EELb1EEENS_21__unordered_map_equalIS2_SZ_NS_8equal_toIS2_EELb1EEENS_9allocatorISZ_EEE21__construct_node_hashIS2_JbEEENS_10unique_ptrINS_11__hash_nodeISZ_PvEENS_22__hash_node_destructorINS18_IS1F_EEEEEEjOT_DpOT0_()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk112__hash_tableINS_17__hash_value_typeI12LegacyOptionN6nonstd8variants7variantIbhjNS4_6detail2TXINS6_2S3EEENS7_INS6_2S4EEENS7_INS6_2S5EEENS7_INS6_2S6EEENS7_INS6_2S7EEENS7_INS6_2S8EEENS7_INS6_2S9EEENS7_INS6_3S10EEENS7_INS6_3S11EEENS7_INS6_3S12EEENS7_INS6_3S13EEENS7_INS6_3S14EEENS7_INS6_3S15EEEEEEENS_22__unordered_map_hasherIS2_SZ_NS_4hashIS2_EELb1EEENS_21__unordered_map_equalIS2_SZ_NS_8equal_toIS2_EELb1EEENS_9allocatorISZ_EEE21__construct_node_hashIS2_JbEEENS_10unique_ptrINS_11__hash_nodeISZ_PvEENS_22__hash_node_destructorINS18_IS1F_EEEEEEjOT_DpOT0_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
