/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk111__partitionIRZN3mce21SimpleResourceTrackerINS_10shared_ptrINS1_21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS1_6BufferENS1_21ClientResourcePointerINS1_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS1_22UncheckedHandleTrackerENSC_17BufferDescriptionEEES3_EEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISK_SF_SG_EES3_EEEENS6_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS1_21PerFrameHandleTrackerESG_EEEENS_8weak_ptrIS1G_EEE19resetValidityChecksEvEUlRS1J_E_NS_11__wrap_iterIPS1J_EEEET0_S1R_S1R_T_NS_26bidirectional_iterator_tagE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk111__partitionIRZN3mce21SimpleResourceTrackerINS_10shared_ptrINS1_21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS1_6BufferENS1_21ClientResourcePointerINS1_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS1_22UncheckedHandleTrackerENSC_17BufferDescriptionEEES3_EEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISK_SF_SG_EES3_EEEENS6_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS1_21PerFrameHandleTrackerESG_EEEENS_8weak_ptrIS1G_EEE19resetValidityChecksEvEUlRS1J_E_NS_11__wrap_iterIPS1J_EEEET0_S1R_S1R_T_NS_26bidirectional_iterator_tagE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk111__partitionIRZN3mce21SimpleResourceTrackerINS_10shared_ptrINS1_21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS1_6BufferENS1_21ClientResourcePointerINS1_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS1_22UncheckedHandleTrackerENSC_17BufferDescriptionEEES3_EEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISK_SF_SG_EES3_EEEENS6_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS1_21PerFrameHandleTrackerESG_EEEENS_8weak_ptrIS1G_EEE19resetValidityChecksEvEUlRS1J_E_NS_11__wrap_iterIPS1J_EEEET0_S1R_S1R_T_NS_26bidirectional_iterator_tagE()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk111__partitionIRZN3mce21SimpleResourceTrackerINS_10shared_ptrINS1_21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS1_6BufferENS1_21ClientResourcePointerINS1_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS1_22UncheckedHandleTrackerENSC_17BufferDescriptionEEES3_EEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISK_SF_SG_EES3_EEEENS6_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS1_21PerFrameHandleTrackerESG_EEEENS_8weak_ptrIS1G_EEE19resetValidityChecksEvEUlRS1J_E_NS_11__wrap_iterIPS1J_EEEET0_S1R_S1R_T_NS_26bidirectional_iterator_tagE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
