/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk16vectorINS_4pairINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS3_6BufferENS3_21ClientResourcePointerINS3_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS3_22UncheckedHandleTrackerENSC_17BufferDescriptionEEENS_10shared_ptrEEEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISL_SF_SG_EESI_EEEENS6_6detail2TXINSP_2S4EEENSQ_INSP_2S5EEENSQ_INSP_2S6EEENSQ_INSP_2S7EEENSQ_INSP_2S8EEENSQ_INSP_2S9EEENSQ_INSP_3S10EEENSQ_INSP_3S11EEENSQ_INSP_3S12EEENSQ_INSP_3S13EEENSQ_INSP_3S14EEENSQ_INSP_3S15EEEEENS3_21PerFrameHandleTrackerESG_EEEENS_10unique_ptrINS3_21ITransactionContainerENS_14default_deleteIS1K_EEEEEENS_9allocatorIS1O_EEE13__move_assignERS1R_NS_17integral_constantIbLb1EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk16vectorINS_4pairINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS3_6BufferENS3_21ClientResourcePointerINS3_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS3_22UncheckedHandleTrackerENSC_17BufferDescriptionEEENS_10shared_ptrEEEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISL_SF_SG_EESI_EEEENS6_6detail2TXINSP_2S4EEENSQ_INSP_2S5EEENSQ_INSP_2S6EEENSQ_INSP_2S7EEENSQ_INSP_2S8EEENSQ_INSP_2S9EEENSQ_INSP_3S10EEENSQ_INSP_3S11EEENSQ_INSP_3S12EEENSQ_INSP_3S13EEENSQ_INSP_3S14EEENSQ_INSP_3S15EEEEENS3_21PerFrameHandleTrackerESG_EEEENS_10unique_ptrINS3_21ITransactionContainerENS_14default_deleteIS1K_EEEEEENS_9allocatorIS1O_EEE13__move_assignERS1R_NS_17integral_constantIbLb1EEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk16vectorINS_4pairINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS3_6BufferENS3_21ClientResourcePointerINS3_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS3_22UncheckedHandleTrackerENSC_17BufferDescriptionEEENS_10shared_ptrEEEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISL_SF_SG_EESI_EEEENS6_6detail2TXINSP_2S4EEENSQ_INSP_2S5EEENSQ_INSP_2S6EEENSQ_INSP_2S7EEENSQ_INSP_2S8EEENSQ_INSP_2S9EEENSQ_INSP_3S10EEENSQ_INSP_3S11EEENSQ_INSP_3S12EEENSQ_INSP_3S13EEENSQ_INSP_3S14EEENSQ_INSP_3S15EEEEENS3_21PerFrameHandleTrackerESG_EEEENS_10unique_ptrINS3_21ITransactionContainerENS_14default_deleteIS1K_EEEEEENS_9allocatorIS1O_EEE13__move_assignERS1R_NS_17integral_constantIbLb1EEE()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk16vectorINS_4pairINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS6_9monostateENS3_6BufferENS3_21ClientResourcePointerINS3_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS4_ISE_NS3_22UncheckedHandleTrackerENSC_17BufferDescriptionEEENS_10shared_ptrEEEEENSA_INSB_INSD_27ResolvedIndexBufferResourceENS4_ISL_SF_SG_EESI_EEEENS6_6detail2TXINSP_2S4EEENSQ_INSP_2S5EEENSQ_INSP_2S6EEENSQ_INSP_2S7EEENSQ_INSP_2S8EEENSQ_INSP_2S9EEENSQ_INSP_3S10EEENSQ_INSP_3S11EEENSQ_INSP_3S12EEENSQ_INSP_3S13EEENSQ_INSP_3S14EEENSQ_INSP_3S15EEEEENS3_21PerFrameHandleTrackerESG_EEEENS_10unique_ptrINS3_21ITransactionContainerENS_14default_deleteIS1K_EEEEEENS_9allocatorIS1O_EEE13__move_assignERS1R_NS_17integral_constantIbLb1EEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
