/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk116allocator_traitsINS_9allocatorIPK11BlockLegacyEEE25__construct_range_forwardIS4_S4_S4_S4_EENS_9enable_ifIXaaaasr31is_trivially_move_constructibleIT0_EE5valuesr7is_sameIT1_T2_EE5valueooL_ZNS_17integral_constantIbLb1EE5valueEEntsr15__has_constructIS5_PS9_RT_EE5valueEvE4typeERS5_PSF_SK_RSE_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk116allocator_traitsINS_9allocatorIPK11BlockLegacyEEE25__construct_range_forwardIS4_S4_S4_S4_EENS_9enable_ifIXaaaasr31is_trivially_move_constructibleIT0_EE5valuesr7is_sameIT1_T2_EE5valueooL_ZNS_17integral_constantIbLb1EE5valueEEntsr15__has_constructIS5_PS9_RT_EE5valueEvE4typeERS5_PSF_SK_RSE_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk116allocator_traitsINS_9allocatorIPK11BlockLegacyEEE25__construct_range_forwardIS4_S4_S4_S4_EENS_9enable_ifIXaaaasr31is_trivially_move_constructibleIT0_EE5valuesr7is_sameIT1_T2_EE5valueooL_ZNS_17integral_constantIbLb1EE5valueEEntsr15__has_constructIS5_PS9_RT_EE5valueEvE4typeERS5_PSF_SK_RSE_()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk116allocator_traitsINS_9allocatorIPK11BlockLegacyEEE25__construct_range_forwardIS4_S4_S4_S4_EENS_9enable_ifIXaaaasr31is_trivially_move_constructibleIT0_EE5valuesr7is_sameIT1_T2_EE5valueooL_ZNS_17integral_constantIbLb1EE5valueEEntsr15__has_constructIS5_PS9_RT_EE5valueEvE4typeERS5_PSF_SK_RSE_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
