/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk110unique_ptrIA_PNS_16__hash_node_baseIPNS_11__hash_nodeINS_17__hash_value_typeIN6nonstd8variants7variantI13ActorUniqueIDNS_4pairI8BlockPos11AutomaticIDI9DimensioniEEENS5_6detail2TXINSE_2S2EEENSF_INSE_2S3EEENSF_INSE_2S4EEENSF_INSE_2S5EEENSF_INSE_2S6EEENSF_INSE_2S7EEENSF_INSE_2S8EEENSF_INSE_2S9EEENSF_INSE_3S10EEENSF_INSE_3S11EEENSF_INSE_3S12EEENSF_INSE_3S13EEENSF_INSE_3S14EEENSF_INSE_3S15EEEEENS0_I35LodestoneCompassComponentCalculatorNS_14default_deleteIS19_EEEEEEPvEEEENS_25__bucket_list_deallocatorINS_9allocatorIS1I_EEEEE5resetIPS1I_EENS_9enable_ifIXsr28_CheckArrayPointerConversionIT_EE5valueEvE4typeES1S_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk110unique_ptrIA_PNS_16__hash_node_baseIPNS_11__hash_nodeINS_17__hash_value_typeIN6nonstd8variants7variantI13ActorUniqueIDNS_4pairI8BlockPos11AutomaticIDI9DimensioniEEENS5_6detail2TXINSE_2S2EEENSF_INSE_2S3EEENSF_INSE_2S4EEENSF_INSE_2S5EEENSF_INSE_2S6EEENSF_INSE_2S7EEENSF_INSE_2S8EEENSF_INSE_2S9EEENSF_INSE_3S10EEENSF_INSE_3S11EEENSF_INSE_3S12EEENSF_INSE_3S13EEENSF_INSE_3S14EEENSF_INSE_3S15EEEEENS0_I35LodestoneCompassComponentCalculatorNS_14default_deleteIS19_EEEEEEPvEEEENS_25__bucket_list_deallocatorINS_9allocatorIS1I_EEEEE5resetIPS1I_EENS_9enable_ifIXsr28_CheckArrayPointerConversionIT_EE5valueEvE4typeES1S_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk110unique_ptrIA_PNS_16__hash_node_baseIPNS_11__hash_nodeINS_17__hash_value_typeIN6nonstd8variants7variantI13ActorUniqueIDNS_4pairI8BlockPos11AutomaticIDI9DimensioniEEENS5_6detail2TXINSE_2S2EEENSF_INSE_2S3EEENSF_INSE_2S4EEENSF_INSE_2S5EEENSF_INSE_2S6EEENSF_INSE_2S7EEENSF_INSE_2S8EEENSF_INSE_2S9EEENSF_INSE_3S10EEENSF_INSE_3S11EEENSF_INSE_3S12EEENSF_INSE_3S13EEENSF_INSE_3S14EEENSF_INSE_3S15EEEEENS0_I35LodestoneCompassComponentCalculatorNS_14default_deleteIS19_EEEEEEPvEEEENS_25__bucket_list_deallocatorINS_9allocatorIS1I_EEEEE5resetIPS1I_EENS_9enable_ifIXsr28_CheckArrayPointerConversionIT_EE5valueEvE4typeES1S_()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk110unique_ptrIA_PNS_16__hash_node_baseIPNS_11__hash_nodeINS_17__hash_value_typeIN6nonstd8variants7variantI13ActorUniqueIDNS_4pairI8BlockPos11AutomaticIDI9DimensioniEEENS5_6detail2TXINSE_2S2EEENSF_INSE_2S3EEENSF_INSE_2S4EEENSF_INSE_2S5EEENSF_INSE_2S6EEENSF_INSE_2S7EEENSF_INSE_2S8EEENSF_INSE_2S9EEENSF_INSE_3S10EEENSF_INSE_3S11EEENSF_INSE_3S12EEENSF_INSE_3S13EEENSF_INSE_3S14EEENSF_INSE_3S15EEEEENS0_I35LodestoneCompassComponentCalculatorNS_14default_deleteIS19_EEEEEEPvEEEENS_25__bucket_list_deallocatorINS_9allocatorIS1I_EEEEE5resetIPS1I_EENS_9enable_ifIXsr28_CheckArrayPointerConversionIT_EE5valueEvE4typeES1S_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
