/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEEN4xbox8services9AllocatorIcEEEEN9rapidjson15GenericDocumentINSA_4UTF8IcEENSA_19MemoryPoolAllocatorINSA_12CrtAllocatorEEESF_EEEENS_19__map_value_compareIS9_SI_NS_4lessIS9_EELb1EEENS7_ISI_EEE16__construct_nodeIJRKNS_21piecewise_construct_tENS_5tupleIJRKS9_EEENST_IJEEEEEENS_10unique_ptrINS_11__tree_nodeISI_PvEENS_22__tree_node_destructorINS7_IS11_EEEEEEDpOT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEEN4xbox8services9AllocatorIcEEEEN9rapidjson15GenericDocumentINSA_4UTF8IcEENSA_19MemoryPoolAllocatorINSA_12CrtAllocatorEEESF_EEEENS_19__map_value_compareIS9_SI_NS_4lessIS9_EELb1EEENS7_ISI_EEE16__construct_nodeIJRKNS_21piecewise_construct_tENS_5tupleIJRKS9_EEENST_IJEEEEEENS_10unique_ptrINS_11__tree_nodeISI_PvEENS_22__tree_node_destructorINS7_IS11_EEEEEEDpOT_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEEN4xbox8services9AllocatorIcEEEEN9rapidjson15GenericDocumentINSA_4UTF8IcEENSA_19MemoryPoolAllocatorINSA_12CrtAllocatorEEESF_EEEENS_19__map_value_compareIS9_SI_NS_4lessIS9_EELb1EEENS7_ISI_EEE16__construct_nodeIJRKNS_21piecewise_construct_tENS_5tupleIJRKS9_EEENST_IJEEEEEENS_10unique_ptrINS_11__tree_nodeISI_PvEENS_22__tree_node_destructorINS7_IS11_EEEEEEDpOT_()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEEN4xbox8services9AllocatorIcEEEEN9rapidjson15GenericDocumentINSA_4UTF8IcEENSA_19MemoryPoolAllocatorINSA_12CrtAllocatorEEESF_EEEENS_19__map_value_compareIS9_SI_NS_4lessIS9_EELb1EEENS7_ISI_EEE16__construct_nodeIJRKNS_21piecewise_construct_tENS_5tupleIJRKS9_EEENST_IJEEEEEENS_10unique_ptrINS_11__tree_nodeISI_PvEENS_22__tree_node_destructorINS7_IS11_EEEEEEDpOT_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
