/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt6__ndk16vectorINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS5_9monostateENS2_6BufferENS2_21ClientResourcePointerINS2_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS3_ISD_NS2_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENS_10shared_ptrEEEEENS9_INSA_INSC_27ResolvedIndexBufferResourceENS3_ISK_SE_SF_EESH_EEEENS5_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS2_21PerFrameHandleTrackerESF_EEEENS_9allocatorIS1H_EEE5eraseENS_11__wrap_iterIPKS1H_EES1O_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNSt6__ndk16vectorINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS5_9monostateENS2_6BufferENS2_21ClientResourcePointerINS2_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS3_ISD_NS2_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENS_10shared_ptrEEEEENS9_INSA_INSC_27ResolvedIndexBufferResourceENS3_ISK_SE_SF_EESH_EEEENS5_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS2_21PerFrameHandleTrackerESF_EEEENS_9allocatorIS1H_EEE5eraseENS_11__wrap_iterIPKS1H_EES1O_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('_ZNSt6__ndk16vectorINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS5_9monostateENS2_6BufferENS2_21ClientResourcePointerINS2_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS3_ISD_NS2_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENS_10shared_ptrEEEEENS9_INSA_INSC_27ResolvedIndexBufferResourceENS3_ISK_SE_SF_EESH_EEEENS5_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS2_21PerFrameHandleTrackerESF_EEEENS_9allocatorIS1H_EEE5eraseENS_11__wrap_iterIPKS1H_EES1O_()');
  },

  /**
   * Called synchronously when about to return from _ZNSt6__ndk16vectorINS_8weak_ptrIN3mce21ResourceBlockTemplateIN6nonstd8variants7variantINS5_9monostateENS2_6BufferENS2_21ClientResourcePointerINS2_15ResourcePointerIN6dragon4mesh28ResolvedVertexBufferResourceENS3_ISD_NS2_22UncheckedHandleTrackerENSB_17BufferDescriptionEEENS_10shared_ptrEEEEENS9_INSA_INSC_27ResolvedIndexBufferResourceENS3_ISK_SE_SF_EESH_EEEENS5_6detail2TXINSO_2S4EEENSP_INSO_2S5EEENSP_INSO_2S6EEENSP_INSO_2S7EEENSP_INSO_2S8EEENSP_INSO_2S9EEENSP_INSO_3S10EEENSP_INSO_3S11EEENSP_INSO_3S12EEENSP_INSO_3S13EEENSP_INSO_3S14EEENSP_INSO_3S15EEEEENS2_21PerFrameHandleTrackerESF_EEEENS_9allocatorIS1H_EEE5eraseENS_11__wrap_iterIPKS1H_EES1O_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
